#!/bin/busybox ash

/bin/busybox --install -s /bin

mount -t devtmpfs devtmpfs -o nosuid /dev
mount -t proc proc -o nosuid,nodev,noexec /proc
mount -t sysfs sys -o nosuid,nodev,noexec /sys

cat /etc/motd

mdev -sd

modprobe virtio_pci
modprobe virtio_blk
modprobe squashfs

mkdir /newroot
mount /dev/vda /newroot

mount --move /dev /newroot/dev
mount --move /proc /newroot/proc
mount --move /sys /newroot/sys

exec switch_root /newroot /sbin/init
