variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

default:
  image: docker.io/library/rust:1.75
  cache:
    paths:
      - .cargo
      - target

stages:
  - check

check:
  stage: check
  before_script:
    - rustc --version && cargo --version
    - rustup component add clippy
    - rustup component add rustfmt
    - cargo install cargo-deny
  script:
    - cargo deny check
    - cargo fmt --all -- --check
    - cargo clippy
