[package]
name = "elusive"
version = "0.1.0"
authors = ["Valentin Finini <valentin.finini@cysec.systems>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
env_logger = "0.7.1"
libc = "0.2.66"
log = "0.4.8"
serde = { version = "1.0.104", features = ["derive"] }
tempfile = "3.1.0"
toml = "0.5.5"

[dependencies.goblin]
version = "0.1.2"
default_features = false
features = ["std", "elf32", "elf64", "endian_fd"]
