[package]
name = "elusive"
version = "0.4.0"
authors = ["Valentin Finini <farenjihn@gmail.com>"]
edition = "2018"

[[bin]]
name = "elusive"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.37"
clap = "2.33.3"
env_logger = "0.8.2"
flate2 = "1.0.19"
libc = "0.2.81"
log = "0.4.11"
toml = "0.5.8"
walkdir = "2.3.1"
zstd = "0.6.0"

[dependencies.object]
version = "0.23.0"
default-features = false
features = ["elf", "read_core", "std"]

[dependencies.serde]
version = "1.0.118"
features = ["derive"]
