[package]
name = "elusive"
version = "0.2.3"
authors = ["Valentin Finini <valentin.finini@cysec.systems>"]
edition = "2018"

[dependencies]
anyhow = "1.0.34"
clap = "2.33.3"
env_logger = "0.8.1"
flate2 = "1.0.19"
fs_extra = "1.2.0"
libc = "0.2.80"
log = "0.4.11"
tempfile = "3.1.0"
toml = "0.5.7"
walkdir = "2.3.1"
zstd = "0.5.3"

[dependencies.goblin]
version = "0.2.3"
default_features = false
features = ["std", "elf32", "elf64", "endian_fd"]

[dependencies.serde]
version = "1.0.117"
features = ["derive"]
