[package]
name = "elusive"
version = "0.1.0"
authors = ["Valentin Finini <valentin.finini@cysec.systems>"]
edition = "2018"

[dependencies]
goblin = "0.1.1"
libc = "0.2.65"
serde = { version = "1.0.102", features = ["derive"] }
serde_derive = "1.0.102"
tempfile = "3.1.0"
toml = "0.5.5"
