[package]
name = "elusive"
version = "0.2.2"
authors = ["Valentin Finini <valentin.finini@cysec.systems>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
cpio = "0.2.0"
env_logger = "0.7.1"
flate2 = "1.0.13"
fs_extra = "1.1.0"
libc = "0.2.66"
log = "0.4.8"
tempfile = "3.1.0"
toml = "0.5.5"
walkdir = "2.3.1"

[dependencies.goblin]
version = "0.1.3"
default_features = false
features = ["std", "elf32", "elf64", "endian_fd"]

[dependencies.serde]
version = "1.0.104"
features = ["derive"]
