[package]
name = "elusive"
version = "0.3.0"
authors = ["Valentin Finini <valentin.finini@cysec.systems>"]
edition = "2018"

[[bin]]
name = "elusive"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.37"
clap = "2.33.3"
env_logger = "0.8.2"
flate2 = "1.0.19"
libc = "0.2.81"
log = "0.4.11"
toml = "0.5.8"
walkdir = "2.3.1"
zstd = "0.6.0"

[dependencies.goblin]
version = "0.3.0"
default_features = false
features = ["std", "elf32", "elf64", "endian_fd"]

[dependencies.serde]
version = "1.0.118"
features = ["derive"]
