[package]
name = "elusive"
version = "0.2.3"
authors = ["Valentin Finini <valentin.finini@cysec.systems>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
clap = "2.33.0"
env_logger = "0.7.1"
flate2 = "1.0.14"
fs_extra = "1.1.0"
libc = "0.2.69"
log = "0.4.8"
tempfile = "3.1.0"
toml = "0.5.6"
walkdir = "2.3.1"

[dependencies.goblin]
version = "0.2.1"
default_features = false
features = ["std", "elf32", "elf64", "endian_fd"]

[dependencies.serde]
version = "1.0.106"
features = ["derive"]
