[package]
name = "elusive"
version = "0.6.1"
authors = ["Valentin Finini <farenjihn@gmail.com>"]
description = "A custom initramfs generator"
license = "GPL-3.0"
repository = "https://github.com/Farenjihn/elusive"
edition = "2018"

[[bin]]
name = "elusive"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.41"
clap = "2.33.3"
env_logger = "0.8.4"
flate2 = "1.0.20"
libc = "0.2.97"
log = "0.4.14"
toml = "0.5.8"
walkdir = "2.3.2"
zstd = "0.9.0"

[dependencies.object]
version = "0.25.3"
default-features = false
features = ["elf", "read_core", "std"]

[dependencies.serde]
version = "1.0.126"
features = ["derive"]
