[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"
yanked = "warn"

[licenses]
unlicensed = "deny"
copyleft = "allow"
allow-osi-fsf-free = "both"
default = "deny"
confidence-threshold = 0.9
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
]

[bans]
multiple-versions = "warn"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
