[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"

[licenses]
confidence-threshold = 0.9
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "GPL-3.0",
    "MIT",
    "Unicode-DFS-2016",
]

[bans]
multiple-versions = "warn"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
