[initramfs]
init = "init"

[[initramfs.bin]]
path = "/bin/busybox"

[[initramfs.bin]]
path = "/sbin/cryptsetup"

[[initramfs.lib]]
path = "/lib64/ld-linux-x86-64.so.2"

[[initramfs.module]]
name = "btrfs"

[microcode]
amd = "/lib/firmware/amd-ucode"
intel = "/lib/firmware/intel-ucode"
