#!/bin/busybox ash

/bin/busybox --install -s /bin

mount -t devtmpfs devtmpfs -o nosuid /dev
mount -t proc proc -o nosuid,nodev,noexec /proc
mount -t sysfs sys -o nosuid,nodev,noexec /sys

modprobe tpm_tis tpm_crb

if [ -e /dev/tpmrm0 ]; then
    echo -e "TPM successfully detected !\n"
else
    echo -e "TPM was not detected !\n"
fi

cat /etc/motd

PS1="root@initramfs \\$ " sh

poweroff -f
