[initramfs]
path = "initramfs"
init = "init"

# [initramfs.modules]
# release = "5.3.11-arch1-1"

[[initramfs.bin]]
path = "/usr/bin/busybox"

[[initramfs.bin]]
path = "/usr/bin/cryptsetup"

[[initramfs.lib]]
path = "/usr/lib/ld-linux-x86-64.so.2"
