name: base
binaries:
  - /usr/bin/busybox
  - /usr/bin/kmod
  - /usr/bin/mount
  - /usr/bin/sulogin
  - /usr/bin/umount
  - /usr/lib64/ld-linux-x86-64.so.2
files:
  - sources:
      - files/systemd/etc/group
      - files/systemd/etc/initrd-release
      - files/systemd/etc/nsswitch.conf
      - files/systemd/etc/passwd
      - files/systemd/etc/shadow
    destination: /etc
symlinks:
  - source: busybox
    destination: /usr/bin/sh
  - source: kmod
    destination: /usr/bin/depmod
  - source: kmod
    destination: /usr/bin/modprobe
---
name: systemd
binaries:
  - /usr/bin/journalctl
  - /usr/bin/systemctl
  - /usr/bin/systemd-tmpfiles
  - /usr/lib/systemd/system-generators/systemd-fstab-generator
  - /usr/lib/systemd/system-generators/systemd-gpt-auto-generator
  - /usr/lib/systemd/systemd
  - /usr/lib/systemd/systemd-fsck
  - /usr/lib/systemd/systemd-journald
  - /usr/lib/systemd/systemd-modules-load
  - /usr/lib/systemd/systemd-shutdown
  - /usr/lib/systemd/systemd-sulogin-shell
  - /usr/lib/systemd/systemd-sysctl
files:
  - sources:
      - /usr/lib/systemd/system/basic.target
      - /usr/lib/systemd/system/emergency.service
      - /usr/lib/systemd/system/emergency.target
      - /usr/lib/systemd/system/final.target
      - /usr/lib/systemd/system/initrd-cleanup.service
      - /usr/lib/systemd/system/initrd-fs.target
      - /usr/lib/systemd/system/initrd-parse-etc.service
      - /usr/lib/systemd/system/initrd-root-device.target
      - /usr/lib/systemd/system/initrd-root-fs.target
      - /usr/lib/systemd/system/initrd-switch-root.service
      - /usr/lib/systemd/system/initrd-switch-root.target
      - /usr/lib/systemd/system/initrd.target
      - /usr/lib/systemd/system/kmod-static-nodes.service
      - /usr/lib/systemd/system/local-fs-pre.target
      - /usr/lib/systemd/system/local-fs.target
      - /usr/lib/systemd/system/paths.target
      - /usr/lib/systemd/system/reboot.target
      - /usr/lib/systemd/system/rescue.service
      - /usr/lib/systemd/system/rescue.target
      - /usr/lib/systemd/system/shutdown.target
      - /usr/lib/systemd/system/slices.target
      - /usr/lib/systemd/system/sockets.target
      - /usr/lib/systemd/system/swap.target
      - /usr/lib/systemd/system/sysinit.target
      - /usr/lib/systemd/system/systemd-fsck@.service
      - /usr/lib/systemd/system/systemd-journald-audit.socket
      - /usr/lib/systemd/system/systemd-journald-dev-log.socket
      - /usr/lib/systemd/system/systemd-journald.service
      - /usr/lib/systemd/system/systemd-journald.socket
      - /usr/lib/systemd/system/systemd-modules-load.service
      - /usr/lib/systemd/system/systemd-reboot.service
      - /usr/lib/systemd/system/systemd-tmpfiles-setup-dev.service
      - /usr/lib/systemd/system/timers.target
      - /usr/lib/systemd/system/umount.target
    destination: /usr/lib64/systemd/system
symlinks:
  - source: initrd.target
    destination: /lib/systemd/system/default.target
  - source: reboot.target
    destination: /lib/systemd/system/ctrl-alt-del.target
  - source: ../kmod-static-nodes.service
    destination: /lib/systemd/system/sysinit.target.wants/kmod-static-nodes.service
  - source: ../systemd-journald.service
    destination: /lib/systemd/system/sysinit.target.wants/systemd-journald.service
  - source: ../systemd-journald.socket
    destination: /lib/systemd/system/sockets.target.wants/systemd-journald.socket
  - source: ../systemd-journald-audit.socket
    destination: /lib/systemd/system/sockets.target.wants/systemd-journald-audit.socket
  - source: ../systemd-journald-dev-log.socket
    destination: /lib/systemd/system/sockets.target.wants/systemd-journald-dev-log.socket
  - source: ../systemd-modules-load.service
    destination: /lib/systemd/system/sysinit.target.wants/systemd-modules-load.service
  - source: ../systemd-tmpfiles-setup-dev.service
    destination: /lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup-dev.service
---
name: udev
binaries:
  - /usr/bin/udevadm
  - /usr/lib/systemd/systemd-udevd
files:
  - sources:
      - /usr/lib/udev/ata_id
      - /usr/lib/udev/scsi_id
    destination: /usr/lib/udev
  - sources:
      - /usr/lib/udev/rules.d/50-udev-default.rules
      - /usr/lib/udev/rules.d/60-persistent-storage.rules
      - /usr/lib/udev/rules.d/64-btrfs.rules
      - /usr/lib/udev/rules.d/80-drivers.rules
      - /usr/lib/udev/rules.d/99-systemd.rules
    destination: /usr/lib/udev/rules.d
  - sources:
      - /usr/lib/systemd/system/initrd-udevadm-cleanup-db.service
      - /usr/lib/systemd/system/systemd-udev-trigger.service
      - /usr/lib/systemd/system/systemd-udevd-control.socket
      - /usr/lib/systemd/system/systemd-udevd-kernel.socket
      - /usr/lib/systemd/system/systemd-udevd.service
    destination: /usr/lib64/systemd/system
symlinks:
  - source: ../systemd-udevd.service
    destination: /lib/systemd/system/sysinit.target.wants/systemd-udevd.service
  - source: ../systemd-udev-trigger.service
    destination: /lib/systemd/system/sysinit.target.wants/systemd-udev-trigger.service
  - source: ../systemd-udevd-control.socket
    destination: /lib/systemd/system/sockets.target.wants/systemd-udevd-control.socket
  - source: ../systemd-udevd-kernel.socket
    destination: /lib/systemd/system/sockets.target.wants/systemd-udevd-kernel.socket
