name: cryptsetup
boot_modules:
  - aesni_intel
  - cbc
  - crc32_generic
  - crc32c_generic
  - dm-bufio
  - dm-crypt
  - ecb
  - xts
binaries:
  - /usr/bin/blkid
  - /usr/bin/cryptsetup
  - /usr/bin/dmsetup
  - /usr/bin/systemd-tty-ask-password-agent
  - /usr/lib/systemd/system-generators/systemd-cryptsetup-generator
  - /usr/lib/systemd/systemd-cryptsetup
  - /usr/lib64/libgcc_s.so.1
files:
  - sources:
      - /lib/udev/rules.d/10-dm.rules
      - /lib/udev/rules.d/13-dm-disk.rules
      - /lib/udev/rules.d/95-dm-notify.rules
      - files/systemd/udev/11-dm-initramfs.rules
    destination: /usr/lib/udev/rules.d
  - sources:
      - /usr/lib/systemd/system/cryptsetup.target
      - /usr/lib/systemd/system/cryptsetup-pre.target
      - /usr/lib/systemd/system/systemd-ask-password-console.path
      - /usr/lib/systemd/system/systemd-ask-password-console.service
    destination: /lib/systemd/system
symlinks:
  - source: ../cryptsetup.target
    destination: /lib/systemd/system/sysinit.target.wants/cryptsetup.target
  - source: ../systemd-ask-password-console.path
    destination: /lib/systemd/system/sysinit.target.wants/systemd-ask-password-console.path
