init: files/basic/init
settings:
  decompress_modules: true
module:
  name: virtualization
  boot_modules:
    - virtio_blk
    - virtio_pci
    - squashfs
  binaries:
    - /usr/bin/busybox
    - /usr/bin/cryptsetup
    - /usr/bin/lsblk
    - /usr/lib64/ld-linux-x86-64.so.2
  files:
    - sources:
        - files/basic/motd
      destination: /etc
