[package]
name = "kmod-sys"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[build-dependencies]
anyhow = "1.0.56"

[build-dependencies.bindgen]
version = "0.59.2"
default_features = false
