name: device-mapper
kernel_modules:
  - dm-bufio
binaries:
  - dmsetup
files:
  - sources:
      - /usr/lib/udev/rules.d/10-dm.rules
      - /usr/lib/udev/rules.d/13-dm-disk.rules
      - /usr/lib/udev/rules.d/95-dm-notify.rules
      - contrib/files/udev/11-dm-initramfs.rules
    destination: /usr/lib/udev/rules.d
