name: systemd-crypt
kernel_modules:
  - aesni_intel
  - cbc
  - dm-crypt
  - ecb
  - xts
binaries:
  - cryptsetup
  - systemd-cryptsetup
  - systemd-cryptsetup-generator
  - /usr/lib64/cryptsetup/libcryptsetup-token-systemd-fido2.so
  - /usr/lib64/cryptsetup/libcryptsetup-token-systemd-pkcs11.so
  - /usr/lib64/cryptsetup/libcryptsetup-token-systemd-tpm2.so
units:
  # target
  - cryptsetup.target
  # path
  - systemd-ask-password-console.path
  # service
  - systemd-ask-password-console.service
