name: tpm2
binaries:
  - /usr/lib/cryptsetup/libcryptsetup-token-systemd-tpm2.so
  - /usr/lib/libtss2-esys.so.0
  - /usr/lib/libtss2-mu.so.0
  - /usr/lib/libtss2-rc.so.0
  - /usr/lib/libtss2-sys.so.1
  - /usr/lib/libtss2-tcti-device.so.0
