[package]
name = "elusive"
version = "0.9.0"
authors = ["Valentin Finini <farenjihn@gmail.com>"]
description = "A custom initramfs generator"
license = "GPL-3.0"
repository = "https://github.com/Farenjihn/elusive"
edition = "2021"

[[bin]]
name = "elusive"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.66"
env_logger = "0.9.3"
flate2 = "1.0.24"
libc = "0.2.137"
log = "0.4.17"
thiserror = "1.0.37"
toml = "0.5.9"
walkdir = "2.3.2"
xz2 = "0.1.7"
zstd = "0.11.2"

[dependencies.clap]
version = "4.0.22"
features = ["derive"]

[dependencies.object]
version = "0.29.0"
default-features = false
features = ["elf", "read_core", "std"]

[dependencies.serde]
version = "1.0.147"
features = ["derive"]

[dependencies.kmod-sys]
path = "../kmod-sys"
