[package]
name = "elusive"
version = "0.10.0"
authors = ["Valentin Finini <farenjihn@gmail.com>"]
description = "A custom initramfs generator"
license = "GPL-3.0"
repository = "https://github.com/Farenjihn/elusive"
edition = "2021"

[[bin]]
name = "elusive"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.70"
env_logger = "0.10.0"
flate2 = "1.0.25"
libc = "0.2.140"
log = "0.4.17"
thiserror = "1.0.40"
toml = "0.7.3"
walkdir = "2.3.3"
xz2 = "0.1.7"
zstd = "0.12.3+zstd.1.5.2"

[dependencies.clap]
version = "4.1.11"
features = ["derive"]

[dependencies.object]
version = "0.30.3"
default-features = false
features = ["elf", "read_core", "std"]

[dependencies.serde]
version = "1.0.157"
features = ["derive"]

[dependencies.kmod-sys]
path = "../kmod-sys"
