[package]
name = "elusive"
version = "0.11.0"
authors = ["Valentin Finini <farenjihn@gmail.com>"]
description = "A custom initramfs generator"
license = "GPL-3.0"
repository = "https://github.com/Farenjihn/elusive"
edition = "2021"

[[bin]]
name = "elusive"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.70"
env_logger = "0.10.0"
flate2 = "1.0.26"
libc = "0.2.142"
log = "0.4.17"
num_cpus = "1.15.0"
serde_yaml = "0.9.21"
thiserror = "1.0.40"
walkdir = "2.3.3"
xz2 = "0.1.7"

[dependencies.clap]
version = "4.2.5"
features = ["derive"]

[dependencies.object]
version = "0.31.0"
default-features = false
features = ["elf", "read_core", "std"]

[dependencies.serde]
version = "1.0.160"
features = ["derive"]

[dependencies.zstd]
version = "0.12.3+zstd.1.5.2"
features = ["zstdmt"]

[dependencies.kmod-sys]
path = "../kmod-sys"
