[[initramfs.bin]]
path = "/bin/mount"

[[initramfs.bin]]
path = "/bin/umount"

[[initramfs.bin]]
path = "/bin/kmod"

[[initramfs.symlink]]
path = "/bin/depmod"
link = "kmod"

[[initramfs.symlink]]
path = "/bin/modprobe"
link = "kmod"

# -------------------------------

[[initramfs.bin]]
path = "/sbin/sulogin"

[[initramfs.bin]]
path = "/bin/busybox"

[[initramfs.symlink]]
path = "/usr/bin/sh"
link = "busybox"

# -------------------------------

[[initramfs.bin]]
path = "/lib/systemd/systemd"
keep_path = true

[[initramfs.bin]]
path = "/lib/systemd/systemd-fsck"
keep_path = true

[[initramfs.bin]]
path = "/lib/systemd/systemd-udevd"
keep_path = true

[[initramfs.bin]]
path = "/lib/systemd/systemd-sysctl"
keep_path = true

[[initramfs.bin]]
path = "/lib/systemd/systemd-journald"
keep_path = true

[[initramfs.bin]]
path = "/lib/systemd/systemd-modules-load"
keep_path = true

[[initramfs.bin]]
path = "/lib/systemd/systemd-sulogin-shell"
keep_path = true

[[initramfs.bin]]
path = "/lib/systemd/systemd-shutdown"
keep_path = true

# -------------------------------

[[initramfs.bin]]
path = "/bin/udevadm"

[[initramfs.bin]]
path = "/bin/systemctl"

[[initramfs.bin]]
path = "/bin/journalctl"

[[initramfs.bin]]
path = "/bin/systemd-tmpfiles"

# -------------------------------

[[initramfs.bin]]
path = "/lib/systemd/system-generators/systemd-fstab-generator"
keep_path = true

[[initramfs.bin]]
path = "/lib/systemd/system-generators/systemd-gpt-auto-generator"
keep_path = true

# -------------------------------

[[initramfs.lib]]
path = "/lib64/ld-linux-x86-64.so.2"

[[initramfs.lib]]
path = "/lib64/libnss_files.so.2"

# -------------------------------

[[initramfs.tree]]
path = "/etc"
copy = [
    "initramfs/systemd/etc/initrd-release",
    "initramfs/systemd/etc/group",
    "initramfs/systemd/etc/passwd",
    "initramfs/systemd/etc/shadow",
    "initramfs/systemd/etc/nsswitch.conf",
]

# -------------------------------

[[initramfs.tree]]
path = "/usr/lib/udev"
copy = [
    "/lib/udev/ata_id",
    "/lib/udev/scsi_id",
]

[[initramfs.tree]]
path = "/usr/lib/udev/rules.d"
copy = [
    "/lib/udev/rules.d/50-udev-default.rules",
    "/lib/udev/rules.d/60-persistent-storage.rules",
    "/lib/udev/rules.d/64-btrfs.rules",
    "/lib/udev/rules.d/80-drivers.rules",
    "/lib/udev/rules.d/99-systemd.rules",
]

# -------------------------------

[[initramfs.tree]]
path = "/lib/systemd/system"
copy = [
    "/lib/systemd/system/basic.target",
    "/lib/systemd/system/emergency.service",
    "/lib/systemd/system/emergency.target",
    "/lib/systemd/system/final.target",
    "/lib/systemd/system/initrd-cleanup.service",
    "/lib/systemd/system/initrd-fs.target",
    "/lib/systemd/system/initrd-parse-etc.service",
    "/lib/systemd/system/initrd-root-device.target",
    "/lib/systemd/system/initrd-root-fs.target",
    "/lib/systemd/system/initrd-switch-root.service",
    "/lib/systemd/system/initrd-switch-root.target",
    "/lib/systemd/system/initrd-udevadm-cleanup-db.service",
    "/lib/systemd/system/initrd.target",
    "/lib/systemd/system/kmod-static-nodes.service",
    "/lib/systemd/system/local-fs-pre.target",
    "/lib/systemd/system/local-fs.target",
    "/lib/systemd/system/paths.target",
    "/lib/systemd/system/reboot.target",
    "/lib/systemd/system/rescue.service",
    "/lib/systemd/system/rescue.target",
    "/lib/systemd/system/shutdown.target",
    "/lib/systemd/system/slices.target",
    "/lib/systemd/system/sockets.target",
    "/lib/systemd/system/swap.target",
    "/lib/systemd/system/sysinit.target",
    "/lib/systemd/system/systemd-fsck@.service",
    "/lib/systemd/system/systemd-journald-audit.socket",
    "/lib/systemd/system/systemd-journald-dev-log.socket",
    "/lib/systemd/system/systemd-journald.service",
    "/lib/systemd/system/systemd-journald.socket",
    "/lib/systemd/system/systemd-modules-load.service",
    "/lib/systemd/system/systemd-reboot.service",
    "/lib/systemd/system/systemd-tmpfiles-setup-dev.service",
    "/lib/systemd/system/systemd-udev-trigger.service",
    "/lib/systemd/system/systemd-udevd-control.socket",
    "/lib/systemd/system/systemd-udevd-kernel.socket",
    "/lib/systemd/system/systemd-udevd.service",
    "/lib/systemd/system/timers.target",
    "/lib/systemd/system/umount.target",
]

# -------------------------------

[[initramfs.symlink]]
path = "/lib/systemd/system/default.target"
link = "initrd.target"

[[initramfs.symlink]]
path = "/lib/systemd/system/ctrl-alt-del.target"
link = "reboot.target"

# -------------------------------

[[initramfs.symlink]]
path = "/lib/systemd/system/sockets.target.wants/systemd-journald-audit.socket"
link = "../systemd-journald-audit.socket"

[[initramfs.symlink]]
path = "/lib/systemd/system/sockets.target.wants/systemd-journald-dev-log.socket"
link = "../systemd-journald-dev-log.socket"

[[initramfs.symlink]]
path = "/lib/systemd/system/sockets.target.wants/systemd-journald.socket"
link = "../systemd-journald.socket"

[[initramfs.symlink]]
path = "/lib/systemd/system/sockets.target.wants/systemd-udevd-control.socket"
link = "../systemd-udevd-control.socket"

[[initramfs.symlink]]
path = "/lib/systemd/system/sockets.target.wants/systemd-udevd-kernel.socket"
link = "../systemd-udevd-kernel.socket"

[[initramfs.symlink]]
path = "/lib/systemd/system/sysinit.target.wants/kmod-static-nodes.service"
link = "../kmod-static-nodes.service"

[[initramfs.symlink]]
path = "/lib/systemd/system/sysinit.target.wants/systemd-journald.service"
link = "../systemd-journald.service"

[[initramfs.symlink]]
path = "/lib/systemd/system/sysinit.target.wants/systemd-modules-load.service"
link = "../systemd-modules-load.service"

[[initramfs.symlink]]
path = "/lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup-dev.service"
link = "../systemd-tmpfiles-setup-dev.service"

[[initramfs.symlink]]
path = "/lib/systemd/system/sysinit.target.wants/systemd-udev-trigger.service"
link = "../systemd-udev-trigger.service"

[[initramfs.symlink]]
path = "/lib/systemd/system/sysinit.target.wants/systemd-udevd.service"
link = "../systemd-udevd.service"
